spring:
  profiles:
    active: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME:bavneeksingh8174@gmail.com}
    password: ${SMTP_PASSWORD:udpjuytwctnqwgwe}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /api

app:
  jwt:
    secret: "dGhpcyBpcyBhIHZlcnkgbG9uZyBzZWNyZXQga2V5IGZvciBKV1QgdG9rZW4gc2lnbmluZyBpbiB0aGUgbGVhdmUgbWFuYWdlciBhcHBsaWNhdGlvbg=="
    expiration-ms: 86400000  # 24 hours
